#!/bin/bash
mkdir -p ~/.ssh
mv ~/authorized_keys ~/.ssh/

[[ -d ~/r ]] || ln -s /mnt/v1/st ~/r

git clone https://github.com/spencertipping/dotfiles ~/dotfiles
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

# Initialize dotfiles
~/dotfiles/setup yes-really

# Setup for motley conf management
mkdir -p ~/bin

source ~/.bashrc
