#!/bin/bash
mkdir -p ~/.ssh
mv ~/authorized_keys ~/.ssh/

# Some git repositories I tend to use
clone() {
  for r; do
    git clone git://github.com/spencertipping/$r ~/$r
  done
}

mkdir -p ~/r
clone bashrc-tmux bash-hats bash-lambda bash-prompt cd \
      dotfiles motley nfu ni perl-objects quickdupe zerovpn

git clone git://github.com/syl20bnr/spacemacs.git ~/.emacs.d
git clone http://xiphosuran:8180/infrastructure/resources ~/resources

# Initialize dotfiles
~/dotfiles/setup yes-really

# Setup for motley conf management
echo '# MOTLEYGEN' > ~/.ssh/config.motley
echo '# MOTLEYGEN' > ~/.bash_aliases.motley

~/motley/motley -f ~/resources/Motfile conf

# Create a bin dir, just for good measure
mkdir ~/bin
